### PR TITLE
Root - axios and react-icons packages added

### PR DESCRIPTION
**Pull request by dazzlerkumar**

### CODE REVIEW

**Comment by hanisntsolo** [comment]
Pls raise against dev. Not master.

**Comment by hanisntsolo** [comment]
@anisha299 pls ensure we are branching from dev.

**Comment by hanisntsolo** [comment]
@dazzlerkumar we don't have explicit interface to test these changes from client end?

**Comment by dazzlerkumar** [comment]
@hanisntsolo These are just architectural changes for the future development. I didn't develop anything.

**Pull request merged**
